name: mod-build
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/mekanism/Mekanism/archive/4a78cb65b11fac7403a12ba141f34c5228a929ca.zip
      Pack_Name: 4a78cb65b11fac7403a12ba141f34c5228a929ca
      Open_Pack_Name: Mekanism-4a78cb65b11fac7403a12ba141f34c5228a929ca
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ${{ env.Open_Pack_Name }}
        path: /opt/libs/
